### ISSUE TITLE
Callbacks are called multiple times

### ISSUE THREAD

**Issue by Whyser** [Pushwoosh/pushwoosh-unity#1]
It was quite some time since we upgraded Pushwoosh but now we finally did. We removed all old stuff and replaced it completely with the new version. However, there's an annoying bug. Callbacks gets called multiple times (tested on Android right now).

For example, the code below will be called twice on start:
    void onRegisteredForPushNotifications(string token)
    {
        Debug.LogError("ABC: ID: " + this.GetInstanceID()); //I added this debug log
        OnRegisteredForPushNotifications (token);
# if UNITY_IPHONE && !UNITY_EDITOR

```
    IOSPushNotificationsManager.OnRegisteredForPushNotifications -= onRegisteredForPushNotifications;
```
# elif UNITY_ANDROID && !UNITY_EDITOR

```
    AndroidPushNotificationsManager.OnRegisteredForPushNotifications -= onRegisteredForPushNotifications;
```
# elif (UNITY_WP8 || UNITY_WP8_1) && !UNITY_EDITOR

```
    WP8PushNotificationsManager.OnRegisteredForPushNotifications -= onRegisteredForPushNotifications;
```
# endif

```
}
```

And the same for `onPushNotificationsReceived` every time. First I thought that maybe I had two instances of the Pushwoosh-object therefore I printed the instance id but that wasn't the problem. So it seems there's something on native level (/GCM related)? 

I actually believe we also experienced this issue on iOS version.

(I can't seem to format the code correctly on GitHub)

**Comment by DimanAM** [comment]
Fixed. Please try latest plugin version.
