### ISSUE TITLE
Not able to assign id to local notification.

### ISSUE THREAD

**Issue by basilbthoppil** [Pushwoosh/pushwoosh-unity#11]
To clear notification using _ClearLocalNotification_ we should be able to set an id to the local notification.

It's very difficult to manage user old scheduled notifications, without proper clearLocalNotification function.

NB: (I think this feature is missing in android sdk as well). @DimanAM

**Comment by basilbthoppil** [comment]
I am okay passing the id also with extras.

**Comment by DimanAM** [comment]
`ScheduleLocalNotification` returns a notification id and `ClearLocalNotification` accepts this id as parameter. There is no need in setting id manually.
