### ISSUE TITLE
Using Badge Number on Android optional?

### ISSUE THREAD

**Issue by Russel1** [Pushwoosh/pushwoosh-unity#12]
Hello,

we have a problem with the badge permissions. These permissions are displayed in the Play Store as new permissions and prevent automatic update our users. Can you make this permissions somehow optional? Unfortunately, are the permissions in the PushwooshUnityPlugin.aar.
We need a better access to this permissions:

```
<uses-permission android:name="com.sec.android.provider.badge.permission.READ"/>
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE"/>

<!--for htc-->
<uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS"/>
<uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT"/>

<!--for sony-->
<uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE"/>

<!--for apex-->
<uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT"/>

<!--for solid-->
<uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE"/>
```

Best regards,
Oli

**Comment by DimanAM** [comment]
Android badge permissions has been moved to the separate [PushwooshBadges.aar](https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Plugins/Android/PushwooshBadges.aar) library. This library is optional and can be safely removed.

**Comment by Russel1** [comment]
Thank you for the fast fix!
