### ISSUE TITLE
In-app Product and In-app Purchase Tag

### ISSUE THREAD

**Issue by Russel1** [Pushwoosh/pushwoosh-unity#16]
How can I tag the In-app Product and In-app Purchase with the Unity Plugin?

**Comment by Russel1** [comment]
no solution?

**Comment by wfhm** [comment]
Hi,

We've just released a new (1.10.0) version of our Unity plugin with a support of In-app Product and In-app Purchase. You can now use [sendPurchase](https://github.com/Pushwoosh/pushwoosh-unity/blob/master/Documentation/Pushwoosh.md#sendpurchase) method to set these values. 

Please update to the latest plugin version and let us know about the results.
