### ISSUE TITLE
iOS 10 SDK Update

### ISSUE THREAD

**Issue by xtiandiaz** [Pushwoosh/pushwoosh-unity#17]
Hi, recently we got a notification about updating the iOS SDK ASAP, due to changes in the way push notifications are treated in iOS 10:

> Due to the changes in iOS 10 you need to upgrade your Pushwoosh iOS SDK as soon as possible. The latest version 4.1.2 of the SDK is fully compatible with iOS 10 devices.

Does the current version of the plugin take into account those changes? If not, can the compiled classes contained in the plugin be replaced with those in the iOS SDK repo?

Thanks!

**Comment by DimanAM** [comment]
The current version of plugin is compatible with iOS10.

**Comment by Russel1** [comment]
But the Unity-Pushwoosh SDK based on version 4.0.9 of the iOS SDK (Commit on Jul 13, 2016).
We need not the latest version 4.1.2 of the SDK?

**Comment by shaders** [comment]
It based on 4.1.0 is works fine with iOS 10
