### ISSUE TITLE
Using android.permission.RECEIVE_BOOT_COMPLETED optional?

### ISSUE THREAD

**Issue by Russel1** [Pushwoosh/pushwoosh-unity#20]
Hello,

we don't need the RECEIVE_BOOT_COMPLETED permission on Android. Can you make this permission somehow optional? Unfortunately, the permission is in the PushwooshUnityPlugin.aar.
We need a better access to this permission.

Best regards,
Oli

**Comment by viridanti** [comment]
Hello,

Thanks for your suggestion! We will make this permission optional in the future updates.

**Comment by DimanAM** [comment]
Fixed in 1.10.0
