### ISSUE TITLE
Get local notification via GetLaunchNotification

### ISSUE THREAD

**Issue by xtiandiaz** [Pushwoosh/pushwoosh-unity#21]
Could it be possible to also get local notifications (i.e. non-push) through `GetLaunchNotification`? In iOS, we're scheduling those using `UnityEngine.iOS.NotificationServices` but their content isn't retrieved when launching the App from them.

**Comment by viridanti** [comment]
Hi,

Actually, on iOS this method works for a push notification only. On Android, however, it could be used to get a local notification.

**Comment by xtiandiaz** [comment]
@viridanti  Indeed, this is also why I'm wondering about the possibility to support the feature on iOS too.

**Comment by xtiandiaz** [comment]
Still looking for the possibility to have this behaviour implemented in the plugin, or for some insights about modifying the native interfaces in order to implement it myself. I'd very much appreciate.

**Comment by viridanti** [comment]
Hi,

We will implement this feature in one of the future versions, thanks! I'll update this thread.

**Comment by WilConine** [comment]
Do we Have this solved yet? Is there any way to get the Launch Notification on iOS via Pushwoosh::GetLaunchNotification() or any other method?
Still seems as though scheduling local notes via UnityEngine.iOS.NotificationServices leaves us blind to capturing user's clicking on the local Notes.

**Comment by JimmyDeemo** [comment]
The problem with this is on line 30 of `UnityRuntime.m` where it adds the pushManger's notification center delegate.

```c
void pw_initializePushManager(char *appId, char *appName) {
    NSString *appCodeStr = [[NSString alloc] initWithUTF8String:appId];
    NSString *appNameStr = appName ? [[NSString alloc] initWithUTF8String:appName] :
    [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleDisplayName"];
    [PushNotificationManager initializeWithAppCode:appCodeStr appName:appNameStr];
    
    [[PushNotificationManager pushManager] sendAppOpen];
    [PushNotificationManager pushManager].delegate = (NSObject<PushNotificationDelegate> *)[UIApplication sharedApplication];
    [UNUserNotificationCenter currentNotificationCenter].delegate = [PushNotificationManager pushManager].notificationCenterDelegate;
}
```

This happens at Pushwooh initialisation time meaning that if you need a custom handler it is a) difficult to add and b) Pushwoosh doesn't get the notificatons it needs to. I'll be contacting support about this issue.

**Comment by wfhm** [comment]
@WilConine @xtiandiaz 

Apologies for such a late reply. Local notification callbacks are accessible starting with 5.9.2 release.
