### ISSUE TITLE
Intent cannot launch application if main activity is overridden

### ISSUE THREAD

**Issue by michaelclockstone** [Pushwoosh/pushwoosh-unity#25]
We are using Prime31 plugins in our Unity project that override the default main activity. So e.g. it looks like this:
    `< activity android:name="com.prime31.UnityPlayerNativeActivity" >`
instead of 
    `< activity android:name="com.unity3d.player.UnityPlayerActivity" >`

When the push message is received I get the following error in the Andorid log:

    java.lang.RuntimeException: Unable to start receiver com.pushwoosh.unityplugin.IntentReceiver: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.clockstone.buzzoff/com.unity3d.player.UnityPlayerActivity};

 Note that in an older version of the Pushwoosh Unity this was no problem. It only occurs since we updated to the latest version (Unity v1.11)

Now the IntentReceiver tries to start the activity with the specific name:

`    Intent launchIntent = new Intent(context, UnityPlayerActivity.class);`

whereas in the older version of plugin it was done like this which obviously also works if the main activity class is overridden:

`Intent localIntent2 = getApplicationContext().getPackageManager().getLaunchIntentForPackage(getApplicationContext().getPackageName());`

**Comment by wfhm** [comment]
Fixed in [1.11.1](https://github.com/Pushwoosh/pushwoosh-unity/releases/tag/1.11.1).
