### ISSUE TITLE
Plugin Issues (Unity 4.7.2 compiling to iOS)

### ISSUE THREAD

**Issue by pieshop** [Pushwoosh/pushwoosh-unity#26]
Im using Unity 4.7.2. To get the plugin to work for iOS I have to:

Amend Pushwoosh/Pushwoosh.cs, adding:
public static string ProductName { get; set; }

Amend Pushwoosh/PushNotificationIOS.cs, changing:

protected override void Initialize () 
{
      //pw_initializePushManager(Pushwoosh.ApplicationCode, Application.productName);
      pw_initializePushManager(Pushwoosh.ApplicationCode, Pushwoosh.ProductName);

**Comment by wfhm** [comment]
Fixed in  https://github.com/Pushwoosh/pushwoosh-unity/commit/a2b086a6105b13908981834769d75c30955ddea6.
