### ISSUE TITLE
problem with xcode archive

### ISSUE THREAD

**Issue by afendo** [Pushwoosh/pushwoosh-unity#28]
After updating to Unity 2017.1.0f3, I can't build xcode archive.
XCode Version 8.3.2 

logs:

23241:        [xcode] Undefined symbols for architecture arm64:
23242:        [xcode]   "_inflate", referenced from:
23243:        [xcode]       pushwoosh::unzReadCurrentFile(void*, void*, unsigned int) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23244:        [xcode]      (maybe you meant: _inflate_copyright, _unity_z_inflateGetHeader , _unity_z_inflateInit2_ , _unity_z_inflatePrime , _unity_z_inflate , _inflateUndermine , _il2cpp_z_inflateSyncPoint , _il2cpp_z_inflateSync , _il2cpp_z_inflateGetHeader , _il2cpp_z_inflate_table , _il2cpp_z_inflateInit_ , _il2cpp_z_inflatePrime , _il2cpp_z_inflateReset , _inflate_table , _il2cpp_method_is_inflated , _unity_z_inflateReset , _unity_z_inflateSync , _il2cpp_z_inflateSetDictionary , __Z27scripting_class_is_inflated17ScriptingClassPtr , _il2cpp_z_inflateEnd , __Z49Register_UnityEngine_MeshCollider_get_inflateMeshv , __Z49Register_UnityEngine_MeshCollider_set_inflateMeshv , _unity_z_inflateEnd , _il2cpp_z_inflate , _il2cpp_z_inflateInit2_ , _unity_z_inflateCopy , _unity_z_inflateSyncPoint , _inflate_fast , _MeshCollider_set_inflateMesh_m3947058528 , _il2cpp_z_inflate_copyright , _il2cpp_z_inflateCopy , _unity_z_inflateSetDictionary , _MeshCollider_get_inflateMesh_m3048128112 , _il2cpp_z_inflate_fast , _unity_z_inflateInit_ , _il2cpp_class_is_inflated )
23245:        [xcode]   "_deflate", referenced from:
23246:        [xcode]       pushwoosh::zipWriteInFileInZip(void*, void const*, unsigned int) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23247:        [xcode]       pushwoosh::zipCloseFileInZipRaw(void*, unsigned long, unsigned long) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23248:        [xcode]      (maybe you meant: _unity_z_deflate_copyright, _unity_z_deflateBound , _unity_z_deflateParams , _unity_z_deflatePrime , _unity_z_deflateSetHeader , _unity_z_deflateReset , _il2cpp_z_deflateCopy , _il2cpp_z_deflateTune , _il2cpp_z_deflatePrime , _il2cpp_z_deflateSetHeader , _il2cpp_z_deflateSetDictionary , _il2cpp_z_deflateReset , _il2cpp_z_deflateBound , _unity_z_deflate , _il2cpp_z_deflate , _il2cpp_z_deflateEnd , _unity_z_deflateEnd , _il2cpp_z_deflateParams , _unity_z_deflateInit2_ , _unity_z_deflateCopy , _il2cpp_z_deflateInit2_ , _il2cpp_z_deflateInit_ , _unity_z_deflateInit_ , _unity_z_deflateSetDictionary , _unity_z_deflateTune , _il2cpp_z_deflate_copyright )
23249:        [xcode]   "_crc32", referenced from:
23250:        [xcode]       -[PWZipArchive addFileToZip:newname:] in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23251:        [xcode]       pushwoosh::zipWriteInFileInZip(void*, void const*, unsigned int) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23252:        [xcode]       pushwoosh::unzReadCurrentFile(void*, void*, unsigned int) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23253:        [xcode]      (maybe you meant: _unity_z_crc32_combine, _il2cpp_z_crc32 , _crc32_combine64 , _unity_z_crc32 , _il2cpp_z_crc32_combine )
23254:        [xcode]   "_inflateEnd", referenced from:
23255:        [xcode]       pushwoosh::unzCloseCurrentFile(void*) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23256:        [xcode]      (maybe you meant: _il2cpp_z_inflateEnd, _unity_z_inflateEnd )
23257:        [xcode]   "_inflateInit2_", referenced from:
23258:        [xcode]       pushwoosh::unzOpenCurrentFile3(void*, int*, int*, int, char const*) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23259:        [xcode]      (maybe you meant: _unity_z_inflateInit2_, _il2cpp_z_inflateInit2_ )
23260:        [xcode]   "_deflateEnd", referenced from:
23261:        [xcode]       pushwoosh::zipCloseFileInZipRaw(void*, unsigned long, unsigned long) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23262:        [xcode]      (maybe you meant: _il2cpp_z_deflateEnd, _unity_z_deflateEnd )
23263:        [xcode]   "_deflateInit2_", referenced from:
23264:        [xcode]       pushwoosh::zipOpenNewFileInZip3(void*, char const*, pushwoosh::zip_fileinfo const*, void const*, unsigned int, void const*, unsigned int, char const*, int, int, int, int, int, int, char const*, unsigned long) in Pushwoosh.a(libPushNotificationManager.a-arm64-master.o)
23265:        [xcode]      (maybe you meant: _unity_z_deflateInit2_, _il2cpp_z_deflateInit2_ )
23266:        [xcode] ld: symbol(s) not found for architecture arm64
23267:        [xcode] clang: error: linker command failed with exit code 1 (use -v to see invocation)
23268:        [xcode] ** ARCHIVE FAILED **

**Comment by shaders** [comment]
Hi, it looks like you are missing libz library.

go to Target section (in XCode)
open "Build Phases" tab
open "Link Binaries With Libraries"
click on "+" button
search "libz.tbd"
click on add button
Repeat the same process for libstdc++.tbd library.

**Comment by afendo** [comment]
Hi, thanks for answer.
But it sounds strange...
Why should I make changes to XCode project?
On previous unity version (5.6.2) everything worked fine without any changes in XCode.
So as I understand, it's unity 2017.1 issue?
Or probably I need to adjust something in the iOS configuration in the Unity Editor?

**Comment by wfhm** [comment]
Fixed in [1.11.1](https://github.com/Pushwoosh/pushwoosh-unity/releases/tag/1.11.1).
