### ISSUE TITLE
iOS popup upon launch without our permission

### ISSUE THREAD

**Issue by joaquingrech** [Pushwoosh/pushwoosh-unity#3]
Ok, this is extremely annoying. After installing Unity SDK when I run the app for the first time I get a popup asking if I want push notifications enabled. Basically the first line on the log is:
[UIApplication(Pushwoosh)] Pushwoosh: Initializing application runtime

This is horrible. I didn't even call anything on pushwoosh on my scripts yet. I don't want that popup at all until I decide to ask for push notifications permissions (usually after a few steps on the game). Why would you guys ask pushwoosh to display the notification without our consent? It destroys usability because most people the first time they install the game (without even trying it yet) won't accept push permissions.

**Comment by joaquingrech** [comment]
will it get fixed? it should not call the push initialization at all unless we request it. So that our games don't get that popup on the first second (i get it even during the intro video)

**Comment by DimanAM** [comment]
Push registration is called when you create Pushwoosh with Pushwoosh.Instance. Just move these calls for later execution.
Separate method for push registration will be added in the nearest release.

**Comment by joaquingrech** [comment]
That's exactly what I'm saying it doesn't work. I don't have any script or anything calling pushwoosh instance on my game until a third scene. First scene is a demo video, one script that all it does is play a video and then when done loads the other scene.
No other script, no other code. And I get a popup immediately asking if I want to allow push notifications.

## 

www.echoboom.com

**Comment by DimanAM** [comment]
Maybe you have some gameObject with Pushwoosh.cs (or PushNotificationsiOS.cs) script attached to it?
I just commented https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Scripts/PushNotificator.cs Start() method and there is no popup.

**Comment by joaquingrech** [comment]
No, nothing. The video scene is just one game object with one script to play it and another with the camera. Nothing else. 

## 

www.echoboom.com

**Comment by DimanAM** [comment]
Push registration is called in PushNotificationsiOS.Start(). Try printing call stack there to see when an why it is called.
If it does not help please provide full log with allowed push notifications. If it is possible please provide minimal reproducer as well.

**Comment by joaquingrech** [comment]
Please, this issue is not "closed". It's not nearly fixed.
You have the call on the iOS files (.h, cpp or .a file), check the log, these are the FIRST lines I see on my log, and it's on App open. The Debug.LogError("this should not be printed") I placed on PushNotificationsIOS.Start are not even displayed (hey, i told you i don't even call anything related to pushwoosh on that scene). It is printed if I call the PushNotification from my code. So here it is, the log, before I even get any of my unity code logs printed out, from the first line as soon as I hit play con Xcode:

2016-01-20 16:55:30.147 dogfightelite[552:194192] [PW] [I] +[UIApplication(Pushwoosh)] Pushwoosh: Initializing application runtime

2016-01-20 16:55:30.213 dogfightelite[552:194192] -> registered mono modules 0x101558be0
2016-01-20 16:55:30.557 dogfightelite[552:194192] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
-> applicationDidFinishLaunching()
2016-01-20 16:55:31.656 dogfightelite[552:194192] [PW] [I] -[PushNotificationManager] Will show push notifications alert: 1
-> applicationDidBecomeActive()
2016-01-20 16:55:31.963 dogfightelite[552:194192] [PW] [I] -[PWLocationTracker] location services authorization status has not been determined yet
Init: screen size 1334x750
Initializing Metal device caps
Initialize engine version: 5.3.1p3 (a581c9fffe9f)
2016-01-20 16:55:32.061 dogfightelite[552:194312] [PW] [I] -[PWRequestManager] 
x
|    Pushwoosh request:
| Url:      https://cp.pushwoosh.com/json/1.3/getInApps
| Payload:  {"request":{"device_type":1,"language":"en","application":"xxxx","userId":"4FCEAF91-F7A0-4D00-BBxxxxx","v":"3.0.12.436","hwid":"4FCEAF91-F7A0-4D0xxxx"}}
| Status:   "200 no error"
| Response: {"status_code":210,"status_message":"Application doesn't have any In-Apps","response":null}
x
2016-01-20 16:55:32.174 dogfightelite[552:194359] [PW] [I] -[PWRequestManager] 
x
|    Pushwoosh request:
| Url:      https://cp.pushwoosh.com/json/1.3/registerUser
| Payload:  {"request":{"device_type":1,"application":"xxxx","userId":"4FCEAF91-F7A0-4D00-xxxx","v":"3.0.12.436","hwid":"4FCEAF91-F7A0-4D00-BB6Dxxxx"}}
| Status:   "200 no error"
| Response: {"status_code": 200, "status_message": "OK","response":null}
x
2016-01-20 16:55:32.177 dogfightelite[552:194363] [PW] [I] -[PWRequestManager] 
x
|    Pushwoosh request:
| Url:      https://cp.pushwoosh.com/json/1.3/applicationOpen
| Payload:  {"request":{"device_type":1,"application":"xxxx","userId":"4FCEAF91-F7A0-xxxx","v":"3.0.12.436","hwid":"4FCEAF91-F7A0-4D00xxxx"}}
| Status:   "200 no error"
| Response: {"status_code":200,"status_message":"OK","response":null}
x
2016-01-20 16:55:32.180 dogfightelite[552:194363] [PW] [D] -[PushNotificationManager] sending appOpen completed

AND HERE IS MY FIRST UNITY RELATED LOG I SEE
UnloadTime: 6.993458 ms
qualitymanager
QualityManager:.ctor()
QualityManager:get_Instance()
<loadNextLevel>c__Iterator3:MoveNext()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

**Comment by joaquingrech** [comment]
i also searched on the code for things like:
"sending appOpen completed" or "Initializing application runtime" which I see on your log. Nothing like that is on the code so your library is obviously getting its own life stage before any scene is loaded.

**Comment by DimanAM** [comment]
There is nothing related to notification popup in this log. 
I’ve made a separate method for push registration (there are some other changes in Pushwoosh class, please see the updated documentation and sample project). In a sample application the registration is called on "Subscribe" button click, and that's when you get the popup.
If you still get the popup on start, then you are probably using some other plugin that calls https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instm/UIApplication/registerForRemoteNotifications method.

**Comment by shaders** [comment]
See as per guide here: http://docs.pushwoosh.com/docs/unity-plugin
Pushwoosh.Instance.RegisterForPushNotifications ();

**Comment by unittesting0** [comment]
Sorry for Off-Topic, but I'm trying to figure out which unity method prints "UnloadTime: 4.054333 ms"

**Comment by joaquingrech** [comment]
so why don't you create a new thread/topic and ask there instead of stepping into other people's threads?
