### ISSUE TITLE
Android manifest merge error on build

### ISSUE THREAD

**Issue by jajanpreetsingh** [Pushwoosh/pushwoosh-unity#30]
Hello, I get this error when I am building my unity game for android on Unity 2017.2. A particular node in pushwoosh android manifest fails to merge in build.

If anyone ever encountered this or knows why this is happening, please help me resolve this issue. I have attached the screenshot for related error below.
![capture](https://user-images.githubusercontent.com/26505875/33490747-219719ba-d686-11e7-9315-2efe3bcfac67.PNG)

**Comment by wfhm** [comment]
Hi,

Looks like you have registered 2 GcmReceivers in yourAndroidManifest.xml. Could you please check it and remove one?

**Comment by jajanpreetsingh** [comment]
I tried removing one of them.. It gets re inserted after trying to make a build. Is your plugin compatible with Unity 2017.2???

**Comment by wfhm** [comment]
@jajanpreetsingh 

Apologies for the delay. 5.5.1 version of the plugin definitely works with Unity 2017.2. Please let us know if the issue persistent with this version.

**Comment by wfhm** [comment]
@jajanpreetsingh 

Any news on this one?
