### ISSUE TITLE
calling RegisterForPushNotifications second time will crash app on iOS with Firebase

### ISSUE THREAD

**Issue by num0n1** [Pushwoosh/pushwoosh-unity#31]
Hi, i'm able to reproduce this in a empty project. Using:
macOS 10.12.6
Xcode 9.0.1
Unity 5.6.0f3
Pushwoosh sdk 5.5.4(tried 1.90 as well, same problem)
Firebase sdk 4.4.3
device: iPhone 5s, 10.2.1(tried on another ios11 device, same problem)
Step to reproduce: call RegisterForPushNotifications first, then simply log a firebase event, such as 
> FirebaseAnalytics.LogEvent(FirebaseAnalytics.EventLogin);

then call RegisterForPushNotifications again, app crashes.

There isn't any error log show in Xcode, but im able to getting these by Crashlytics:
![crashlog](https://user-images.githubusercontent.com/20987635/37087214-a0895126-2234-11e8-9fd8-c95e3b5c861c.png)

I did a lot googling, but got no luck, seems no one have had the same problem, everything was fine before until we decided to add Firebase analytics. Im guessing there are some conflicts between the two.
Hope someone can help to take a look, thanks.

**Comment by wfhm** [comment]
Hi,

Checking this one.

**Comment by num0n1** [comment]
want to update, just found out that RegisterForPushNotifications has to be called **before** firebase inits, otherwise will crash

**Comment by wfhm** [comment]
@num0n1 Confirmed, working on the fix.

**Comment by wfhm** [comment]
The fix will be rolled out with the next release.

**Comment by num0n1** [comment]
@wfhm thanks

**Comment by wfhm** [comment]
@num0n1 fixed with 5.6.0

**Comment by reflexing** [comment]
We started to experience this bug after updating Firebase to version 6.2.
We use Firebase Analytics, Crashlytics and Dynamic Links.

**Comment by wfhm** [comment]
@reflexing may I ask you to create a new issue in this repo and provide most actual crash stack trace?
