### ISSUE TITLE
is unity 2018 supported?

### ISSUE THREAD

**Issue by ahmadalli** [Pushwoosh/pushwoosh-unity#32]

**Comment by wfhm** [comment]
@ahmadalli 

The current version does not work with Unity 2018 out of the box. You need to add the following library to your Assets/Plugins/Android directory to make it work: 
 
[common-1.0.3.jar.zip](https://github.com/Pushwoosh/pushwoosh-unity/files/2000346/common-1.0.3.jar.zip)

Unzip it and add the .jar to the directory above.

**Comment by ahmadalli** [comment]
Thanks 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by wfhm** [comment]
@ahmadalli Fully supported starting with 5.8.0 update.
