### ISSUE TITLE
Please use Play services resolver

### ISSUE THREAD

**Issue by rankorn** [Pushwoosh/pushwoosh-unity#33]
It is very hard to maintain multiple Unity plugins with the different play services and support library versions.
Can you add the Play Services Resolver mechanism to your Plugin? 
This will make it easier to use your plugin with Facebook and Google play games.
Thanks

**Comment by wfhm** [comment]
@rankorn 

We have put adding Play Services resolver in our pipeline, however most likely it will not be included in the next release.

**Comment by wfhm** [comment]
@rankorn ,

Added in 5.8.2 version.
