### ISSUE TITLE
Apple AppStore review flags the locationAlwaysInUse feature

### ISSUE THREAD

**Issue by duck4i** [Pushwoosh/pushwoosh-unity#37]
Geozone feature is flagged by Apple to be problematic privacy wise, and we have no way to disable the inclusion of the Geozone feature. The warning from Apple can be cleared by adding new privacy strings, but we (Ubisoft) don't want to be associated with location collection when user is not inside our games. 

Can we get the GeoZone as a part of modular SDK that implementator would include or exclude depending on their needs? For us its really important we don't have things that can worry users inside our games.

This is the warning we got from Apple. 

> Dear Developer,
We identified one or more issues with a recent delivery for your app, "XXXXXXXX". Your delivery was successful, but you may wish to correct the following issues in your next delivery: 
"Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)." 
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect. 
>

**Comment by wfhm** [comment]
@mihailogazda Hey,

This task is already in our backlog. Am I correct that right now it is not yet mandatory and you can still deploy our apps without adding a purpose string at this moment?

**Comment by duck4i** [comment]
@wfhm Thanks for the reply, yes the Apple will enforce the rule starting 1st January, which for us means that due to our release cycle we'd need to update the Pushwoosh in the next release, or soon... Any ETA when this patch is expected to be out? We'd be happy with trying a custom build if thats easier.. Thanks

**Comment by wfhm** [comment]
@mihailogazda 

There is no ETA at the moment, however I will discuss it with the team to see if we can speed it up.

**Comment by wfhm** [comment]
@mihailogazda 

I've got the response, the ETA will be adjusted upon customer requests. As far as I was informed, you are already in contact with our BD team, so I've informed them about this request.

**Comment by duck4i** [comment]
@wfhm  Many thanks!

**Comment by duck4i** [comment]
hey @wfhm, any updates on this? Thanks

**Comment by wfhm** [comment]
@mihailogazda this change is waiting to be deployed in native iOS SDK, after that we will do the same for Unity. Please stay tuned!

**Comment by wfhm** [comment]
@mihailogazda geolocation is moved to a separate framework with a 5.10.0 release.
