### ISSUE TITLE
Assets/Plugins/WP8/PushSDK.dll not allowed or could not be found

### ISSUE THREAD

**Issue by Mojoejoe** [Pushwoosh/pushwoosh-unity#38]
I am having trouble building for Android. I have following exception:

```
ArgumentException: The Assembly System.Device is referenced by PushSDK ('Assets/Plugins/WP8/PushSDK.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:155)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:195)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```
I have found [this topic](https://answers.unity.com/questions/485085/dll-is-not-allowed-to-be-included-or-could-not-be.html), where it is said to change Api Compatibility Level to .NET 2.0. 
After changing that I still cannot build the app.

Has anybody solved this problem?

**Comment by wfhm** [comment]
Hey @Mojoejoe ,

You can solve the issue by deselecting Android platform in Import Settings:

![screen shot 2018-09-21 at 14 45 40](https://user-images.githubusercontent.com/13344781/45867176-0a9f3d00-bdad-11e8-9f4d-bae459c974a6.png)

**Comment by Mojoejoe** [comment]
@wfhm Thank you, that fixed the problem ! I have successfully build for Android.
