### ISSUE TITLE
Android devices get new push registrations upon launch

### ISSUE THREAD

**Issue by joaquingrech** [Pushwoosh/pushwoosh-unity#4]
Since I installed the sdk, pushwoosh websites decides every single launch of the app is a new installation.
So if you launch the app 30 times, pushwoosh website will say you have 30 new users. What gives?
This not only uses accounts that are not real but makes it impossible to monitor and send push to specific devices/users since they get hundredths of different registrations if they play often.

**Comment by shaders** [comment]
That's weird. Could you please paste two console logs from separate app launches?

**Comment by joaquingrech** [comment]
i already talked to someone on support about this and sent them logcat. The logcat says it's always using the same one but on the website i'm getting hundredths of new registrations (and I have less than 80 real installs at this moment). So it may be an issue on the web api.

**Comment by shaders** [comment]
Closing the ticket then.
