### ISSUE TITLE
iOS: Pushwoosh/Pushwoosh.h file not found

### ISSUE THREAD

**Issue by Demy** [Pushwoosh/pushwoosh-unity#42]
I update the plugin from the version 5.4.0 to the version 5.11.0 and it works well on Android, but the build fails on iOS. 

It fails on the xCode build part in **UnityRuntime.m** on the line 9
`#import <Pushwoosh/Pushwoosh.h>`
> 'Pushwoosh/Pushwoosh.h' file not found

Upd: the version 5.9.3 works well, so the error is in the newer version

**Comment by ghqian** [comment]
We have the same problem

**Comment by wfhm** [comment]
@Demy @ghqian checking it.

**Comment by wfhm** [comment]
@Demy @Demy  which Unity version were you using when you got this error?

**Comment by Demy** [comment]
> @Demy @Demy which Unity version were you using when you got this error?

2018.1.1f

**Comment by MahdiGhiasi** [comment]
We're also having the exact same issue with Pushwoosh extension version 5.11.0 and 5.10.0.

Also, our Unity version is 2017.4.1f1.

**Comment by SaraRaees** [comment]
You can put "Pushwoosh.framework" folder from the iOS plugin on to the iOS folder of your project. After that, you can build correctly!

**Comment by wfhm** [comment]
@Demy @ghqian @MahdiGhiasi 

We've just rolled out a new plugin version. Please let us know if the issue persists. 

**Note**: Unity plugin now uses FCM API instead of GCM, and the integration process is changed, so please refer to the updated guide:

https://www.pushwoosh.com/docs/unity-plugin

**Comment by Aisper** [comment]
Hi. I'm using Unity 2018.3.6f1 and Pushwoosh plugin 5.12.1. Still having the issue.

Building on mac, if that might be the case.

**Comment by SaraRaees** [comment]
@wfhm 
I have the same problem in Pushwoosh version 5.14.1. My Unity is 2017.4.24f1.

**Comment by wfhm** [comment]
@SaraRaees 

Just tried building the sample app with the latest (2019.1.4) and with the 2018.3.2 versions, and it worked just fine on our side. We have never reproduced the issue so far, so if you could provide us with a reproducer build, it would really speed up the resolution process. By any chance is it possible for you to share one by sending it to our Support team at help@pushwoosh.com so they could pass it to us?

**Comment by z-haruki-hirama** [comment]
I could not build with Unity 2017.4.30 f1, Pushwoosh 5.17.0.

**Comment by joaquingrech** [comment]
can you please try with the latest 2019.2.6f ? it's not working again to build on ios. This is becoming a real PITA for pushwoosh developers.

**Comment by Harika-mob** [comment]
i Update the cordova ios Platform 7.0.1 and add pushwoosh plugin it shows
 **import <pushwoosh/pushwoosh.h/> file not found error will come** 

can u anyone solve my issue

**Comment by enginseer-dev** [comment]
Hello, @Harika-mob 

Please execute in your project's folder: 
`cordova plugin list`

Pushwoosh plugin should be listed, for example: 
`pushwoosh-cordova-plugin 8.3.17 "Pushwoosh"`

if the Pushwoosh plugin is not in the list of your Cordova plugins, please, double-check that you've executed each step of the integration manual: https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/cordova/integrating-cordova-plugin

**Comment by Harika-mob** [comment]
hii ,@enginseer-dev
Below are my plugins list 

cordova-open-native-settings 1.5.5 "Native settings"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-battery-status 2.0.3 "Battery"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-camera 7.0.0 "Camera"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email-composer 0.10.1 "EmailComposer"
cordova-plugin-file-opener2 4.0.0 "File Opener2"
cordova-plugin-file-transfer 2.0.0 "File Transfer"
cordova-plugin-file 8.0.1 "File"
cordova-plugin-fingerprint-aio 5.0.1 "FingerprintAllInOne"
cordova-plugin-geolocation 5.0.0 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-media-capture 5.0.0 "Capture"
cordova-plugin-media 7.0.0 "Media"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-power-optimization 0.0.3 "PowerOptimization"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-screensize 1.3.1 "screensize"
cordova-plugin-splashscreen 6.0.1 "Splashscreen"
cordova-plugin-statusbar 4.0.0 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-sqlite-storage 6.1.0 "Cordova SQLite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 7.1.4 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"

when my  IOS app is in background it shows  **Thread1 ->PushNotification userNotificationCenter :willPresentNotification :withComplitionHandler**  (Thread 1:EXC_BAD_ACCESS(Code=2 ,address =xxxxxxxx))

Can u Please slove my Issue..

**Comment by enginseer-dev** [comment]
@Harika-mob Pushwoosh plugin is not present in the plugin list of your Cordova project. 

You need to double-check that you've executed each step of the integration manual: https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/cordova/integrating-cordova-plugin

**Comment by Harika-mob** [comment]
Hi ,@enginseer-dev 

my plugin list
cordova-open-native-settings 1.5.5 "Native settings"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-battery-status 2.0.3 "Battery"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-camera 7.0.0 "Camera"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email-composer 0.10.1 "EmailComposer"
cordova-plugin-file-opener2 4.0.0 "File Opener2"
cordova-plugin-file-transfer 2.0.0 "File Transfer"
cordova-plugin-file 8.0.1 "File"
cordova-plugin-fingerprint-aio 5.0.1 "FingerprintAllInOne"
cordova-plugin-geolocation 5.0.0 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-media-capture 5.0.0 "Capture"
cordova-plugin-media 7.0.0 "Media"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-power-optimization 0.0.3 "PowerOptimization"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-screensize 1.3.1 "screensize"
cordova-plugin-splashscreen 6.0.1 "Splashscreen"
cordova-plugin-statusbar 4.0.0 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-sqlite-storage 6.1.0 "Cordova SQLite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 7.1.4 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
pushwoosh-cordova-plugin 8.3.19 "pushwoosh"

when my IOS app is in background it shows Thread1 ->PushNotification userNotificationCenter :willPresentNotification :withComplitionHandler (Thread 1:EXC_BAD_ACCESS(Code=2 ,address =xxxxxxxx))

**Comment by enginseer-dev** [comment]
@Harika-mob Could you confirm if you're using the .xcworkspace file in your project?
This file should be used after adding the plugin.

Additionally, in your iOS project directory, please execute these terminal commands:
```
pod deintegrate
pod install
```
This will refresh your CocoaPods integration.
If the issue persists, consider removing and then reinstalling the iOS platform in your Cordova project:
```
cordova platform rm ios
cordova platform add ios
```

**Comment by Harika-mob** [comment]
Hello ,@engineer-dev

i am using .xcworkspace 
When my IOS app is in the background, it shows Thread1 ->PushNotification userNotificationCenter :willPresentNotification :withComplimentHandler (Thread 1:EXC_BAD_ACCESS(Code=2,address =xxxxxxxx)) This only occurs when my app is installed for the first time.

**Comment by enginseer-dev** [comment]
@Harika-mob The error EXC_BAD_ACCESS typically indicates that the application is trying to access memory that is either not allocated or is outside of its memory space.

Please open the .xcworkspace file in Xcode.
Run the app with the debugger attached (using Xcode).
When the error occurs, Xcode should pause execution and highlight the line of code causing the issue.
This can provide insights into what part of the code is causing the problem.

If the instruction above doesn't help to pinpoint the root of the issue, please, share a reproducer project with us.
You can send it to help@pushwoosh.com and mention this issue in the ticket.

Please, if you will get any additional information related to your issue, create a new issue in the Pushwoosh Cordova repository.
This is a closed Unity issue that is unrelated to the issue you are facing.
