### ISSUE TITLE
Is latest version of pushwoosh ios sdk(5.14.1) compatible with Unity 2017.4.24f1 ?

### ISSUE THREAD

**Issue by threekanjbeen** [Pushwoosh/pushwoosh-unity#48]

**Comment by wfhm** [comment]
Hi @alirezapoorslt!

Checking it

**Comment by wfhm** [comment]
@alirezapoorslt

While we are performing tests, could you please clarify: have you encountered any issues with the latest version of Pushwoosh-Unity plugin(5.14.1) and Unity 2017.4.24f1?
If so, please provide us with more details on this matter, it would be very helpful for us!
