### ISSUE TITLE
Unity 5 incompatibility with Google Play Game Services

### ISSUE THREAD

**Issue by eintopf** [Pushwoosh/pushwoosh-unity#5]
Getting this error when using Pushwoosh and Google Play Game Services:
 E/AndroidRuntime(13033): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID

There is also a "answers" thread (without actual answers...) - would love to see a fix for this:
https://community.pushwoosh.com/questions/2897/unity-plugin-android-javalangclassnotfoundexception-didnt-find-class-comgoogleandroidgmsiidinstanceid

**Comment by DimanAM** [comment]
com/google/android/gms/iid/InstanceID is located in [play-services-gcm-8.4.0.aar](https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Plugins/Android/play-services-gcm-8.4.0.aar).
Did you delete it?

**Comment by eintopf** [comment]
I had to, otherwise the project won't compile, since the Google Play Plugin needs a newer version of the library and Pushwoosh seems to be outdated. 

You can reproduce this issue by importing the gpg from the official site: https://github.com/playgameservices/play-games-plugin-for-unity

and after that add the Pushwoosh Unity plugin. Then try to build.

**Comment by DimanAM** [comment]
I do not see any errors. PushwooshUnitySample compiles well with [Google Play Games plugin](https://github.com/playgameservices/play-games-plugin-for-unity). Do you use latest Pushwoosh plugin?  Have you updated Google Play Services library and Google Repository using Android SDK manager (it seems Google Play Games plugin uses local versions of libraries)

**Comment by DaanKog** [comment]
I think I have the same problem.

I integrated the Pushwoosh Unity Plugin on Android using Unity 5. Followed the instructions strictly. (I am not using any other plugins at this moment)

When I install the game on my Android device, I only get a black screen (not even the splashscreen shows up)
When I delete the Android Manifest from the plugin/android folder, everything runs smoothly (but of course I can not receive messages.) 
I have checked and rechecked the manifest but nothing seems wrong.

Can you fix this somehow?

**Comment by eintopf** [comment]
@DimanAM This is strange, since i'm not the only one having this problem. I integrated the most current version of Pushwoosh. I'll try to find some time to create a reproducible project.

@DaanKog  The issue you are talking about is not related to the one i'm talking about in this issue-thread. The issue i'm talking about is a "tradeoff" between errors with InstanceID vs compile time errors (conflicting jar / aar files).

**Comment by shaders** [comment]
@eintopf just wondering if you had a chance getting reproducible project?

**Comment by DaanKog** [comment]
Hi, no I'm sorry... I stopped trying and decided I would try to find my own
solution. Sorry for not replying :(

DK
Op 2 apr. 2016 20:24 schreef "shaders" notifications@github.com:

**Comment by eintopf** [comment]
Why did you close this? DaanKog did not open this issue? :D
I'm still having trouble with this. I'll upload a reproducible example on Monday or Tuesday - sorry for the delay.

**Comment by eintopf** [comment]
Ok, I tried reproducing it. However the error did not appear in a clean project. So some other library seems to be conflicting, i'm investigating now.

However one further Feedback: Could you please improve the Manifest Workflow? Most plugins have their Manifest Files in a separate folder which in the end are merged together. However therefore there is a need for a editor script which would replace the package name thingy automatically.

**Comment by Legendxh** [comment]
**I modify the Pushwoosh AndroidManifest.xml and it works with all!**

**Im using Google Play Services 0.9.27**

**Here is WORKING AndroidManifest.xml for Pushwoosh and GooglePlayServices**
**Requeriments (IMPORTANT):**
**_-Imported Pushwoosh package in your project files UNCHANGED_**

**Copy all this code**
http://pastebin.com/1Gir8MJY
1. **Replace** it on your **_<ProjectName>/Assets/Plugins/Android/AndroidManifest.xml_**
2. **Delete** **_android-support-v4.js_** (to avoid "Unable to convert classes to dex format" at compile).
3. In **_AndroidManifest.xml search and replace "YOUR_PACKAGE_NAME"_** with your own package name.

**Use it with sample scene script (PushNotificator.cs) for testing :)**

**Comment by QuadomSoft** [comment]
I have this issue too. 
I'm using beside pushwoosh plugin, the google analytics plugin and this requires google play services. 
When i try to build my game i get the error below.
I have a link to my project and has just the google-play-services and pushwoosh plugin if someone want to take a look. 

I'm using Unity Pro - version 5.3.4f1 on Windows 8.1
I tried the "Legendxh" solution but the problem persist.

Thanks and I'm waiting for a feedback!

LINK UNITY PROJECT: https://drive.google.com/open?id=0B7sugb8nMh6RNjEzRUV2LVBzbW8

ERROR: "CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Developer\android-sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Developer/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.android.gms:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.gcm:com.google.android.gms.location -S"

**Comment by DimanAM** [comment]
@Quadom 
Google analytics plugin uses outdated google play library. You can try to update it yourself:

```
rm -rf Assets/Plugins/Android/google-play-services_lib/libs
rm -rf Assets/Plugins/Android/google-play-services_lib/res
cp ${ANDROID_HOME}/extras/google/m2repository/com/google/android/gms/play-services-analytics/8.4.0/play-services-analytics-8.4.0.aar Assets/Plugins/Android/
cp ${ANDROID_HOME}/extras/google/m2repository/com/google/android/gms/play-services-ads/8.4.0/play-services-ads-8.4.0.aar Assets/Plugins/Android/
```

And pray it works.

**Comment by shaders** [comment]
Closing

**Comment by QuadomSoft** [comment]
@DimanAM Unfortunately this still not fix my issue.

**Comment by DimanAM** [comment]
@Quadom This is strange. At least it should compile.
Do you still have the same error log?

Have you replaced the `PACKAGE_NAME` in AndroidManifest.xml?
This step was missing in the project you shared.

**Comment by QuadomSoft** [comment]
@DimanAM  Yes, below is a link to a clean unity project that has just the pushwoosh plugin + google game services and nothing else (NO google analytics plugin). I change the "PACKAGE_NAME" to the bundle ID that i'm using and the problem still exist. If you want, please just try to make a build on android using my source.

https://drive.google.com/open?id=0B7sugb8nMh6RZFhObV9Zd3JQVGc

Thanks a lot for your time and help!

**Comment by unittesting0** [comment]
Sorry for Off-Topic, but I'm trying to figure out which unity method prints "UnloadTime: 4.054333 ms"

**Comment by shaders** [comment]
@unittesting0 please submit a new thread for a new questions.
