### ISSUE TITLE
[Unity SDK 5.22.3 / iOS] Deeplink doesn't come

### ISSUE THREAD

**Issue by yuryshumovsky** [Pushwoosh/pushwoosh-unity#52]
Hi, 

I send push notification message with Deep Link (Actions->DeepLink)
A notification opens an app. After that I read deep link:
`Application.absoluteURL`
https://docs.unity3d.com/ScriptReference/Application-absoluteURL.html
(iOS: If the application has been launched or activated using a URL Scheme or a Universal Link, a deep link (Universal Link) URL.)

Of course I test deeplink locally, it does read correctly but from notification doesn't.

Could you give some information how to read deeplinks from notifications ?

**Comment by wfhm** [comment]
@yuryshumovsky,

You can access payload of a push notification using the onPushNotificationsAccepted() callback. The link comes as a value of the "l" parameter, so you should just check if this key-value pair exists in the push payload and get its value. Keep in mind that payload is returned as a string. Here is a short example of its usage:

https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Scripts/PushNotificator.cs#L34
https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Scripts/PushNotificator.cs#L147
