### ISSUE TITLE
Push woosh Intergration error unity 2020.1.3

### ISSUE THREAD

**Issue by Ludique-Wrks** [Pushwoosh/pushwoosh-unity#56]
Am having an issue getting pushwoosh to work getting error: 

2021/02/21 10:44:58.159 11397 14845 Error Unity AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/Pushwoosh;
2021/02/21 10:44:58.159 11397 14845 Error Unity java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/Pushwoosh;
2021/02/21 10:44:58.159 11397 14845 Error Unity 	at com.pushwoosh.unityplugin.PushwooshProxy.initialize(PushwooshProxy.java:58)
2021/02/21 10:44:58.159 11397 14845 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2021/02/21 10:44:58.159 11397 14845 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2021/02/21 10:44:58.159 11397 14845 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2021/02/21 10:44:58.159 11397 14845 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2021/02/21 10:44:58.159 11397 14845 Error Unity 	at android.os.Looper.loop(Looper.java:246)
2021/02/21 10:44:58.159 11397 14845 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2021/02/21 10:44:58.159 11397 14845 Error Unity Caused by: java.lang.ClassNotFoundException: com.pushwoosh.Pushwoosh
2021/02/21 10:44:58.159 11397 14845 Error Unity 	... 7 more
2021/02/21 10:44:58.159 11397 14845 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
2021/02/21 10:44:58.159 11397 14845 Error Unity   at UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
2021/02/21 10:44:58.159 11397 14845 Error Unity   at PushNotificationsAndroid.Initialize () [0x00000] in <00000000000000
2021/02/21 10:44:58.303 11397 14886 Error Unity -------- GLSL link error:  The number of vertex shader storage blocks (1) is greater than the maximum number allowed (0).
2021/02/21 10:44:58.303 11397 14886 Error Unity 
2021/02/21 10:44:58.303 11397 14886 Error Unity 
2021/02/21 10:44:58.303 11397 14886 Error Unity  
2021/02/21 10:44:58.303 11397 14886 Error Unity (Filename:  Line: 645)
2021/02/21 10:44:58.303 11397 14886 Error Unity

**Comment by wfhm** [comment]
@Ludique-Wrks 

It looks like the dependencies of the plugin were not resolved correctly. Could you please check that Google Resolver has correctly imported the dependencies in your app? It might be a good idea to force resolve it in your project as well.

**Comment by Ludique-Wrks** [comment]
Thank you, force resolve worked, The push notifications work well but am getting an error in my logcat, am pretty sure i used the correct ID

2021/02/24 12:09:46.920 1610 5693 Error Pushwoosh [PushwooshFcmHelper] FCM registration error:INVALID_PARAMETERS

**Comment by wfhm** [comment]
@Ludique-Wrks 
**INVALID_PARAMETERS** is a response from FCM when attempting to get a push token for a device. It indicates that FCM authentication failed, so, most likely, you have either specified the FCM Project Number incorrectly, or the google-services.json file does not match the project it is used for.

Please make sure that the google-services.json includes your app's package name and that it is related to the same project, and that the FCM Sender ID is specified similarly [to this line in our sample](https://github.com/Pushwoosh/pushwoosh-unity/blob/master/PushwooshUnitySample/Assets/Scripts/PushNotificator.cs#L30):
