### ISSUE TITLE
Unity 2021.2.10 Assets/Plugins/Android/[res, assets] build error

### ISSUE THREAD

**Issue by Yaski** [Pushwoosh/pushwoosh-unity#60]
Android build doesn't work using Pushwoosh on Unity 2021.2.10
The reason is that plugin uses Assets/Plugins/Android/res and Assets/Plugins/Android/assets folders. It is not supported anymore.

From the [Docs](https://docs.unity3d.com/2021.2/Documentation/Manual/UpgradeGuide20212.html):

Unity no longer copies Gradle
 project assets located in Assets/Plugins/Android/[res, assets] to the Gradle project.
Previously you could place Gradle resources in this folder and Unity copied them into the Gradle project. You should now use [AAR or androidlib plug-ins](https://docs.unity3d.com/2021.2/Documentation/Manual/AndroidAARPlugins.html) to pass additional Gradle resources to the application.
If you place project assets in this folder, Unity shows a build error message.

**Comment by wfhm** [comment]
@Yaski Got it reproduced. Will be fixed with the next release.

**Comment by Yaski** [comment]
@wfhm Great! Tanks!
Any ETA for the update? We are blocked by this dependency now

**Comment by Yaski** [comment]
I fixed the error by moving res folder in PushWoosh.androidlib subfolder
![image](https://user-images.githubusercontent.com/1292529/155087597-7d756cca-916c-489c-b3bf-b412315693e8.png)

And update MyCustomBuildProcessor change res output path

**Comment by wfhm** [comment]
@Yaski Thanks for sharing this! It worked on our side as well, so this is one of the possible workarounds for now. 

We'll update the CustomBuildProcessor to avoid using Assets/Plugins/Android/[res, assets] and create .aar with resources with the next release.

**Comment by Yaski** [comment]
@wfhm 
It would be good if you fix PushwooshBuildManager too to not use TargetGuidByName because it was deprecated

**Comment by wfhm** [comment]
@Yaski Sure, we will also include this in the next release.

**Comment by wfhm** [comment]
Fixed with the 6.1.0 release.
