### ISSUE TITLE
AndroidJavaException: java.lang.NoClassDefFoundError when initialize plugin

### ISSUE THREAD

**Issue by kimsanbaev-karim** [Pushwoosh/pushwoosh-unity#67]
Hi there.
I cloned https://github.com/Pushwoosh/pushwoosh-unity/tree/master/PushwooshUnitySample and build it on Android.
I have set FcmProjectNumber from Firebase and ApplicationCode from Pushwoosh console.
But when initialize on device exception is thrown

`08-04 14:59:25.757  3651  3712 E BufferQueueProducer: [SurfaceView - com.pushwoosh.demoapp/com.unity3d.player.UnityPlayerActivity@60b4101@0#0] disconnect: not connected (req=1)
08-04 14:59:26.043 15268 15289 E Unity   : AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/Pushwoosh;
08-04 14:59:26.043 15268 15289 E Unity   : java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/Pushwoosh;
08-04 14:59:26.043 15268 15289 E Unity   :      at com.pushwoosh.unityplugin.PushwooshProxy.initialize(PushwooshProxy.java:59)
08-04 14:59:26.043 15268 15289 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-04 14:59:26.043 15268 15289 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
08-04 14:59:26.043 15268 15289 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
08-04 14:59:26.043 15268 15289 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:103)
08-04 14:59:26.043 15268 15289 E Unity   :      at android.os.Looper.loop(Looper.java:237)
08-04 14:59:26.043 15268 15289 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
08-04 14:59:26.043 15268 15289 E Unity   : Caused by: java.lang.ClassNotFoundException: com.pushwoosh.Pushwoosh
08-04 14:59:26.043 15268 15289 E Unity   :      ... 7 more
08-04 14:59:26.043 15268 15289 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00096] in <8d004d142a7a494687c9041b399514ac>:0
08-04 14:59:26.043 15268 15289 E Unity   :   at UnityEngine.AndroidJNISafe.CallStaticVoidMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x0000f] in <8d004d142a7a494687c9041b399514ac>:0
08-04 14:59:26.043 15268 15289 E Unity   :   at UnityEngine.AndroidJavaObject._CallSt`

If press Subscribe:

`08-04 14:59:41.119 15268 15289 E Unity   : NullReferenceException: Object reference not set to an instance of an object
08-04 14:59:41.119 15268 15289 E Unity   :   at PushNotificationsAndroid.RegisterForPushNotifications () [0x0000f] in <ad1234bc8c674ee18fdb7e91531b0c01>:0
08-04 14:59:41.119 15268 15289 E Unity   :   at PushNotificator.OnSubscribe () [0x00005] in <ad1234bc8c674ee18fdb7e91531b0c01>:0
08-04 14:59:41.119 15268 15289 E Unity   :   at UnityEngine.Events.InvokableCall.Invoke () [0x00010] in <db71f4e720664d18afde8b9ba044dc0f>:0
08-04 14:59:41.119 15268 15289 E Unity   :   at UnityEngine.Events.UnityEvent.Invoke () [0x00022] in <db71f4e720664d18afde8b9ba044dc0f>:0
08-04 14:59:41.119 15268 15289 E Unity   :   at UnityEngine.UI.Button.Press () [0x0001c] in <617c7c86e3c3461aaca01b73fc3b0eaf>:0
08-04 14:59:41.119 15268 15289 E Unity   :   at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00009] in <617c7c86e3c3461aaca01b73fc3b0eaf>:0
08-04 14:59:41.119 15268 15289 E Unity   :   at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00007] in <617c7c86e3c3461aaca01b73fc3b0eaf>:0
08-04 14:59:41.119 15268 15289 E Unity   :   at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystem`

**Comment by kimsanbaev-karim** [comment]
It's fine corrrectly on version 6.1.2 (d727226 - Pushwoosh Unity Plugin 6.1.2)

**Comment by wfhm** [comment]
@Karim-K-dev hey,

`Failed resolution of: Lcom/pushwoosh/Pushwoosh; ` error indicates that Pushwoosh Android SDK was not added to the project. Could you please check that Pushwoosh AARs were added to Assets/Plugins/Android? If they weren't then you can use Android Dependency Resolver to force resolve project dependencies. 

The error on clicking Subscribe button should be related to the same issue - you are referring to an instance of Pushwoosh class which does not exist in your project.

**Comment by wfhm** [comment]
Closed as there was no response.
