### ISSUE TITLE
Legacy Firebase API

### ISSUE THREAD

**Issue by kimsanbaev-karim** [Pushwoosh/pushwoosh-unity#68]
In guide https://docs.pushwoosh.com/platform-docs/manage-projects/project-configuration/configure-android-platform
3. In Cloud Messaging tab find Server Key and Sender ID:
Not correct, but Firebase use new API with new UI.

Push nitification not working if using new firebase API. Nothing comes to firebase and there are no logs.
This is bottleneck for everyone who will integrate the plugin in the future, because there are no errors anywhere - they just don’t receive pushes to the device, quietly

For Fix:
Enable and use legacy firebase api with server key for pushwoosh

**Comment by kimsanbaev-karim** [comment]
Update docs for newbies and add logging for admin panel, please

**Comment by wfhm** [comment]
This is not related to the plugin and to Pushwoosh SDK in general. We are aware of the changes on Firebase's side though, and our team is working on this. This issue will be closed, however if you want to track the progress, you can submit a support ticket [here](https://help.pushwoosh.com/hc/en-us/requests/new) and provide a bit more detail on your request.
