### ISSUE TITLE
Game cannot register for notifications on WSA (Pushwoosh Unity plugin 6.1.2)

### ISSUE THREAD

**Issue by reflexing** [Pushwoosh/pushwoosh-unity#69]
Hello, discovered that Pushwoosh Unity plugin 6.1.2 cannot register for notifications on WSA.

Relevant log is:

```
Game: Pushwoosh.OnFailedToRegisteredForPushNotifications: Error ocurred while registering to push notifications: 
Value cannot be null.
Parameter name: s
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
Game.Logger.Unity.SerilogLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Game.Pushwoosh:OnFailedToRegisteredForPushNotifications(String)
Pushwoosh:FailedToRegisteredForPushNotifications(String)
PushNotificationsWindows:TokenError(Object, TokenErrorEventArgs)
PushwooshForWindows.Pushwoosh:internalPushTokenFailed(Object, String)
PushSDK.NotificationService:SendTokenToPushwooshFailed(Object, String)
PushSDK.<InternalSendRequestAsync>d__0:MoveNext()
```

Watching connections with packet sniffer shows that there were no communication attempts to Pushwoosh servers.

We've re-checked game configuration in Pushwoosh console, everything seems to be OK.
What could possibly go wrong?

**Comment by reflexing** [comment]
> Watching connections with packet sniffer shows that there are no communication attempts to Pushwoosh servers.

Disregard that, there was a request to 78.47.243.139.

**Comment by wfhm** [comment]
@reflexing I apologize for such a delayed response! Could you please let us know if the issue still persists?

**Comment by reflexing** [comment]
The PushSDK code was stripped on IL2CPP builds.

I missed `Assets/Pushwoosh/link.xml` while updating plugin and it was deleted. Our manager contacted your support and we discovered it. It works now.

Maybe you should add this file to the plugin?
https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Embed-link.xml-in-UPM-package

Option 2 looks good.

**Comment by wfhm** [comment]
@reflexing Great news! I will discuss it with the team and see if we should indeed add it to the plugin. Thanks for the suggestion!
