### ISSUE TITLE
Notifications are not sent in Unity iOS

### ISSUE THREAD

**Issue by ChikiGuy** [Pushwoosh/pushwoosh-unity#7]
Since the latest update (or the one before), the notifications are not getting send to iOS devices (on 8.4.1).

This is a show stopper since the previous version had crashes on Android.

**Comment by shaders** [comment]
Nothing has been changed in iOS version. What does push history say?

**Comment by ChikiGuy** [comment]
I'll close this. This seems to have been an iOS 8 system issue.
