### ISSUE TITLE
How to use Local Notification IOS?

### ISSUE THREAD

**Issue by firdiar-mita** [Pushwoosh/pushwoosh-unity#72]
Pushwoosh.Instance.ScheduleLocalNotification -> for android

how to implement this on IOS?

**Comment by enginseer-dev** [comment]
Hi @firdiar-mita! Currently, the Pushwoosh Unity plugin does not support iOS local notifications, mostly due to already existing Unity classes. Please utilize the [standard Unity tools](https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.4/manual/iOS.html) for this purpose.

**Comment by wfhm** [comment]
@firdiar-mita Please let me add to our previous reply. 

Some time ago we decided that we do not want to support local notifications in our SDK and plugins at all, focusing on other communication channels (such as push notifications, in-app messages, inbox etc.), as there are multiple third-party tools that serve the same purpose and can be integrated alongside Pushwoosh both on iOS and Android. Could you please let us know if using local notifications provided by Pushwoosh is a must in your integration, or if it is possible to use third-party tools for this purpose? If there is such a reason, could you please let us know about it?
