### ISSUE TITLE
Runtime error: AndroidJavaException: java.lang.ClassNotFoundException: com.pushwoosh.unityplugin.PushwooshProxy

### ISSUE THREAD

**Issue by Tavernari** [Pushwoosh/pushwoosh-unity#9]
Hi,

I am here again, the last commit fix my last issue, thanks a lot.
But now I had other issue.

`AndroidJavaException: java.lang.ClassNotFoundException: com.pushwoosh.unityplugin.PushwooshProxy
                                                            at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
                                                            at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
                                                            at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
                                                            at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
                                                            at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0 
                                                            at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <filename unknown>:0 
                                                            at UnityEngine.AndroidJavaClass..ctor (System.String className) [0x00000] in <filename unknown>:0 
                                                            at PushNotificationsAndroid.Initialize () [0x0000b] in /Users/vtavernari/Doc`

I tried to search some solution before here, and I found an old post about this error, and I found a similar issue. [Page about issue](https://community.pushwoosh.com/questions/340/unity-android-javalangclassnotfoundexception-comarellomobileandroidpushpushwooshproxy)

And the explanation I read was 

> Hi, we've experienced the same issue. After some investigation the root of the problem lies in incorrect version of Java compiler that was used to build UnityPushwoosh.jar library. The jar in question was build with Java 7 compiler that is not supported by Android dex tool and as a result of this the classes are silently removed from final dex compiled binaries which cause the ClassNotFoundException above.
> 
> You can check the version of compiled class files for yourself. Just unpack UnityPushwoosh.jar like this: unzip UnityPushwoosh.jar and then look at the first 8 bytes of any decompressed *class file. The correct sequence in hexadecimal should be as follows: cafe babe 0000 0032. The last byte is version identifier. If you see this: cafe babe 0000 0033 then the binary was compiled with Java 7 thus resulting in ClassNotFoundException when you try to use it at runtime. The simplest solution would be probably for Push Woosh guys to recompile their binary though looking at the current version in GitHub repository it seems to be already compiled properly.

I am using Dex compile in my project. It is a problem? 

My manifest is: 

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.gazeus.euchre"  xmlns:amazon="http://schemas.amazon.com/apk/res/android" android:installLocation="preferExternal" android:theme="@android:style/Theme.NoTitleBar" android:versionName="1.0" android:versionCode="1">
  <application android:name="android.support.multidex.MultiDexApplication">
    <activity android:name="com.custom.project.OurCustomActivtiy" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
        <activity android:name="com.unity3d.player.UnityPlayerActivity" android:launchMode="singleTask" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="PACKAGE_NAME.MESSAGE" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:launchMode="singleTask" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:screenOrientation="portrait">
            <meta-data android:name="android.app.lib_name" android:value="unity" />
            <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
        </activity>
    <activity android:name="com.facebook.unity.FBUnityLoginActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen">
    </activity>
    <activity android:name="com.facebook.LoginActivity" android:configChanges="keyboardHidden|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen">
    </activity>
    <activity android:name="com.facebook.unity.FBUnityDeepLinkingActivity" android:exported="true">
    </activity>
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\000" />
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="PACKAGE_NAME" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="com.pushwoosh.MessageAlertReceiver"
            android:permission="com.amazon.device.messaging.permission.SEND">
            <intent-filter>
                <action android:name="com.amazon.device.messaging.intent.REGISTRATION" />
                <action android:name="com.amazon.device.messaging.intent.RECEIVE" />
                <category android:name="PACKAGE_NAME" />
            </intent-filter>
        </receiver>
        <amazon:enable-feature android:name="com.amazon.device.messaging" android:required="false" />
  </application>
  <uses-feature android:glEsVersion="0x00020000" />
    <uses-sdk android:minSdkVersion="9" android:targetSdkVersion="17" />
    <permission android:name="com.gazeus.euchre.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.gazeus.euchre.permission.C2D_MESSAGE" />
    <permission android:name="com.gazeus.euchre.permission.RECEIVE_ADM_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.gazeus.euchre.permission.RECEIVE_ADM_MESSAGE" />
</manifest>`

**Comment by DimanAM** [comment]
It appears Unity4 does not recognize aar library format. This feature was added in 5.0p1 release and still was not ported in latest 4.x.
